version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  # Ignore log4j, because it's a provided library
  - dependency-name: org.apache.logging.log4j:log4j-core
