# Use https://travis-ci.org/ for automatic testing

# speed up testing https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# This is a java project
language: java

# Compile the project and run unit tests
script: mvn test -B

jdk:
  - oraclejdk8
  - openjdk11

# Cache Maven dependencies
cache:
  directories:
    - '$HOME/.m2/repository'
