# project data for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.bukkit.${project.name}Bukkit

# meta data for plugin managers
authors: [games647, 'https://github.com/games647/ColorConsole/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}
